part of 'app_pages.dart';

abstract class Routes {
  Routes._();
  static const SPLASH = _Paths.SPLASH;
  static const ONBOARDING = _Paths.ONBOARDING;
  static const LOGIN = _Paths.LOGIN;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const PROFILE_SCREEN = _Paths.PROFILE_SCREEN;
  static const REMINDERS = _Paths.REMINDERS;
  static const AFFIRMATIONS = _Paths.AFFIRMATIONS;
  static const THEMES = _Paths.THEMES;
  static const JOURNAL1 = _Paths.JOURNAL1;
  static const JOURNAL2 = _Paths.JOURNAL2;
  static const JOURNAL_REMINDER = _Paths.JOURNAL_REMINDER;
  static const HEAR_ABOUT = _Paths.HEAR_ABOUT;
  static const SUBSCRIPTION_SCREEN = _Paths.SUBSCRIPTION_SCREEN;
  static const ADD_ENTRY = _Paths.ADD_ENTRY;
  static const HOME = _Paths.HOME;
  static const SHARE_SCREEN = _Paths.SHARE_SCREEN;
  static const Journal_Home = _Paths.Journal_Home;
  static const STREAK_SCREEN = _Paths.STREAK_SCREEN;
  static const RESTORE = _Paths.RESTORE;
  static const FREEZE = _Paths.FREEZE;
  static const FILTER = _Paths.FILTER;
  static const MY_LIST = _Paths.MY_LIST;
  static const FAVORITES = _Paths.FAVORITES;
  static const GUEST = _Paths.GUEST;
  static const SETTINGS = _Paths.SETTINGS;
  static const ABOUT_EDIT = _Paths.ABOUT_EDIT;
  static const AFFIRMATION_TYPES = _Paths.AFFIRMATION_TYPES;
  static const APP_THEMES = _Paths.APP_THEMES;
  static const CONTACT_ADMIN = _Paths.CONTACT_ADMIN;
  static const SIGNUP = _Paths.SIGNUP;
  static const AFFIRMATION_REMINDER = _Paths.AFFIRMATION_REMINDER;
  static const FAQ = _Paths.FAQ;
  static const addNewList = _Paths.addNewList;
  static const ADD_AFFIRMATIONS = _Paths.ADD_AFFIRMATIONS;
  static const AddAffirmationBottomSheet = _Paths.AddAffirmationBottomSheet;
  static const PURCHASE_SCREEN = _Paths.PURCHASE_SCREEN;
}

abstract class _Paths {
  _Paths._();
  static const SPLASH = '/splash';
  static const ONBOARDING = '/onboarding';
  static const LOGIN = '/login';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const PROFILE_SCREEN = '/profile-screen';
  static const REMINDERS = '/reminders';
  static const AFFIRMATIONS = '/affirmations';
  static const THEMES = '/themes';
  static const JOURNAL1 = '/journal-view1';
  static const JOURNAL2 = '/journal-view2';
  static const JOURNAL_REMINDER = '/journal-reminder';
  static const HEAR_ABOUT = '/hear-about';
  static const SUBSCRIPTION_SCREEN = '/subscription-screen';
  static const ADD_ENTRY = '/add-entry';
  static const HOME = '/home';
  static const SHARE_SCREEN = '/share-screen';
  static const Journal_Home = '/journal-home';
  static const STREAK_SCREEN = '/streak-screen';
  static const RESTORE = '/restore';
  static const FREEZE = '/freeze';
  static const FILTER = '/filter';
  static const MY_LIST = '/my-list';
  static const FAVORITES = '/favorites';
  static const GUEST = '/guest';
  static const SETTINGS = '/settings';
  static const ABOUT_EDIT = '/about-edit';
  static const AFFIRMATION_TYPES = '/affirmation-types';
  static const APP_THEMES = '/app-themes';
  static const CONTACT_ADMIN = '/contact-admin';
  static const SIGNUP = '/signup';
  static const AFFIRMATION_REMINDER = '/affirmation-reminder';
  static const FAQ = '/faq';
  static const addNewList = '/addNewList';
  static const ADD_AFFIRMATIONS = '/add-affirmations';
  static const AddAffirmationBottomSheet = '/add-affirmation-bottom-sheet';
  static const PURCHASE_SCREEN = '/purchase-screen';
}
